// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://atydwlmsqslqejdnokzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0eWR3bG1zcXNscWVqZG5va3pvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkzNjQwOTksImV4cCI6MjA4NDk0MDA5OX0.GFuNoCIeSeJRGYjQ6DFFCyqufrYbBRztoIyhFANiYjk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});